version: '3.8'
services:
  db:
    build: ./db
    ports:
      - "8000:8000"
    volumes:
      - ./db/app:/app
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:///./test.db
  db-service:
    build: ./db-service
    ports:
      - "8001:8001"
    depends_on:
      - db
    volumes:
    - ./db-service/app:/app
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:///./test.db
  client-service:
    build: ./client
    ports:
      - "8002:8002"
    depends_on:
      - db-service
    volumes:
    - ./client/app:/app
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:///./test.db