name: Docker

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the Docker image'
        required: true
        default: 'latest'
env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push db
        id: docker_build1
        uses: docker/build-push-action@v2
        with:
          context: ./db
          file: ./db/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/db:latest

      - name: Build and push db-service
        id: docker_build2
        uses: docker/build-push-action@v2
        with:
          context: ./db-service
          file: ./db-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/db-service:latest

      - name: Build and push client
          id: docker_build2
          uses: docker/build-push-action@v2
          with:
            context: ./client
            file: ./client/Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/client:latest